[mcp_servers.spec-kit-documentation]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "https://gitmcp.io/github/spec-kit"
]

[mcp_servers.serverless-workflow-specification-documentation]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "https://gitmcp.io/serverlessworkflow/specification"
]

[mcp_servers.serverless-workflow-sdk-typescript-documentation]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "https://gitmcp.io/serverlessworkflow/sdk-typescript"
]

[mcp_servers.rete-js-documentation]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "https://gitmcp.io/retejs/rete"
]

[mcp_servers.rete-lit-plugin-documentation]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "https://gitmcp.io/retejs/lit-plugin"
]

[mcp_servers.react-flow-documentation]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "https://gitmcp.io/xyflow/xyflow"
]